### ISSUE TITLE
Add support for mutations through Go client

### ISSUE THREAD

**Issue by mohitranka** [dgraph-io/dgraphgoclient#3]
As of now, the go-client for dgraph only support querying the graph, however we need the ability to mutate through client as well. [data importers](https://github.com/dgraph-io/dgraph/issues/120) are blocked on this feature.

**Comment by mohitranka** [comment]
@dgraph-io/team  If no one is working on it, I'll take it up.

**Comment by manishrjain** [comment]
You can just send mutation instructions via the query interface, so this should already work. CC: @pawanrawal

**Comment by mohitranka** [comment]
@manishrjain hmm.. ok. Let me check it out.

**Comment by mohitranka** [comment]
Query works with mutations as well. Thanks. Closing the issue as invalid.
