### ISSUE TITLE
Issue in building Go-client

### ISSUE THREAD

**Issue by mohitranka** [dgraph-io/dgraphgoclient#4]
I cloned the `clients` repository  and installed the dependencies via following command.

`go get github.com/golang/protobuf/proto`
`go get golang.org/x/net/context`
`go get google.golang.org/grpc`

on running 

`go run main.go`

I am getting the following error

`dgraphgoclient git:(master) go run main.go`
`# github.com/dgraph-io/clients/dgraphgoclient/graph`
`graph/graphresponse.pb.go:133: undefined: grpc.SupportPackageIsVersion2`

Can anyone confirm that the client builds and/or educate me on how to go about it.

**Comment by manishrjain** [comment]
Please install all the deps in vendor folder.

**Comment by mohitranka** [comment]
@manishrjain There is no vendor folder for this repository.

**Comment by manishrjain** [comment]
Sorry the message was meant for @pawanrawal

**Comment by mohitranka** [comment]
@manishrjain @pawanrawal Thanks. it works now. Closing the issue.
