### ISSUE TITLE
Mutations don't run when using raw string literal.

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraphgoclient#5]
Mutations don't work when using a raw string literal
```
`mutation { set {<alice> <follows> <bob> . \n <alice> <name> "Alice" . \n <bob> <name> "Bob" . }}`
```
 or when double quotes aren't escaped in an interpreted string literal.
```
"mutation { set {<alice> <follows> <bob> . \n <alice> <name> "Alice" . \n <bob> <name> "Bob" . }}"
```

**Comment by mohitranka** [comment]
@pawanrawal Is this an issue with the go-client or server side parsing? If client side, we'll need to make sure that issue does not happen with other language clients as well.

**Comment by pawanrawal** [comment]
I have to go through is and find out more about this. Sure, if it's something specific to the client, I will let you know.

**Comment by pawanrawal** [comment]
Figured out that this is not a bug https://discuss.dgraph.io/t/go-client-mutations/633.

In v0.5 we would provide an easier way for the user to create a batch of mutations.
